version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "app_db"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  next-number-app:
    image: next-number-app-java
    depends_on:
      - "db"
    ports:
      - "8080:1234"
volumes:
  db-data: